CREATE TABLE IF NOT EXISTS server (id INTEGER IDENTITY PRIMARY KEY, hostname VARCHAR(64));
CREATE TABLE IF NOT EXISTS role (id INTEGER IDENTITY PRIMARY KEY, name VARCHAR(64));
CREATE TABLE IF NOT EXISTS serverrole (id INTEGER IDENTITY PRIMARY KEY, serverid INTEGER, roleid INTEGER);
CREATE TABLE IF NOT EXISTS action (id INTEGER IDENTITY PRIMARY KEY, name VARCHAR(64));
CREATE TABLE IF NOT EXISTS protocol (id INTEGER IDENTITY PRIMARY KEY, serverid INTEGER, actionid INTEGER, status INTEGER, errortext VARCHAR(3000), created DATETIME);
